### ISSUE TITLE
TOKEN setup for testing

### ISSUE THREAD

**Issue by mih** [datalad/datalad-ebrains#9]
The token expire way too quickly to be used as a deposited secret in this repo. We need a better setup, likely provided by EBRAINS admin.

**Comment by mih** [comment]
https://services.humanbrainproject.eu/oidc/ ?

**Comment by dickscheid** [comment]
The short token lifecycles are a known restriction, and the EBRAINS Knowledge Graph developers indicated a solution coming up. We will have to get back to them about a timeline.

**Comment by mih** [comment]
I emailed EBRAINS support re permissions to register an OIDC client to be used within the CI (with secrets kept secret). Once we have that, we can follow the example of https://github.com/FZJ-INM1-BDA/siibra-python/pull/204, and move to this kind of auth-workflow.

**Comment by mih** [comment]
I am closing this issue. We have not received a response to ticket 14690 in the past 3 months.
